name: Create and publish a packages
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
        env:
          CI: true

  # release-github-package:
  #   runs-on: ubuntu-latest
  #   needs: npm-test
  #   steps:
  #     - uses: actions/checkout@v2.4.0
  #     - uses: actions/setup-node@v2.5.1
        # Setup .npmrc file to publish to GitHub
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-npm-package:
    runs-on: ubuntu-latest
    needs: npm-test
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
