---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - 'master'
      - release/*
  pull_request:
    branches:
      - master
      - release/*

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_HTML: true
          VALIDATE_BASH: true
          # VALIDATE_PERL: false
          # VALIDATE_PHP_BUILTIN: false
          # VALIDATE_PYTHON: false
          # VALIDATE_RUBY: false
          # VALIDATE_COFFEE: false
          # VALIDATE_ANSIBLE: false
          # VALIDATE_JAVASCRIPT_ES: false
          # VALIDATE_JAVASCRIPT_STANDARD: false
          # VALIDATE_TYPESCRIPT_ES: false
          # VALIDATE_TYPESCRIPT_STANDARD: false
          # VALIDATE_DOCKER: false
          # VALIDATE_GO: false
          # VALIDATE_TERRAFORM: false
          # VALIDATE_CSS: false
          # ANSIBLE_DIRECTORY:
          # ACTIONS_RUNNER_DEBUG: false
          # DEFAULT_WORKSPACE:
